name: deploy-dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: set build number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> "$BUILD_NUMBER"
      - name: build docker image 
        run: docker build -t myapp:${BUILD_NUMBER} .
      - name: Show docker images
        run: docker images