name: deploy-dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t ecommerce:${{ github.run_number }} .
        
      - name: Show docker images
        run: docker images