name: deploy-dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t ecommerce:${{ github.run_number }} .

      - name: Show docker images
        run: docker images

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Test AWS credentials
        run: aws sts get-caller-identity